### ISSUE TITLE
redirecting .git urls as well

### ISSUE THREAD

**Issue by thomasjungblut** [cloudfoundry/go-fetcher#2]
We try to retrieve the CF cli using [echocat's gradle plugin](https://github.com/echocat/gradle-golang-plugin). 

However, when we define the dependency like this:

```
dependencies {
        build 'code.cloudfoundry.org/cli'

        vcsRepositoryProvider('git', 'code.cloudfoundry.org/', 'GitHubCF', '^(?<root>code\\.cloudfoundry\\.org/(?<repo>[A-Za-z0-9_.\\-]+))(?<subPath>/[A-Za-z0-9_.\\-]+)*$')
}
```

The plugin would try to resolve this using a .git extension, which results in 404.
```
Fetch remote refs from https://code.cloudfoundry.org/cli.git...
```

Now I know that this is a bit out of scope since this only supports `go get`, but would it be possible for you to also match .git urls?

**Comment by mjj209** [comment]
I'm reviewing your issue with our development team, and will get back to you by next week. Would you really want a feature that would let you `git clone https://code.cloudfoundry.org/cli` (with or without the .git suffix) ? And would you want to redirect all of the sub-modules as well?

**Comment by thomasjungblut** [comment]
Thanks for getting back so fast. 
Yes, including ".git" suffix for the URL should be sufficient for it to follow the redirect and retrieve the project.

**Comment by mjj209** [comment]
Hi Thomas,

After reviewing the issue with our development team, and comparing the priority of improvements to the go-fetcher service, we have decided that it will be difficult to prioritize this work. We will keep this in mind if we decide to make major improvements to the service.

The concerns are around the surface area that this change would effect. This is quite a lot of work, especially when we consider the recursive nature of the sub-modules. To do this feature correctly would require a large effort, and the gain is not high enough at this point.

Thanks,
Mike J
PM@Pivotal

**Comment by thomasjungblut** [comment]
Hey Mike,

That's really unfortunate, because this is the only package that obstructs us from making our builds fully reproducible. We tried different tools like gopkg.in, bazel and glide. But none of that made it possible to go through your go-fetcher and retrieve with a specific version. 

We vendored the full CLI package now, which is less than ideal because of its sheer size.
